services:

  postgres:
    image: postgres:16
    container_name: medicare_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: medicare_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - medicare_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d medicare_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  medicare_data: